[package]
name = "squack"
version = "0.4.0"
authors = ["Kiley Owen <yelikdev@gmail.com>"]

[dependencies]
actule = {git = "https://github.com/yeliknewo/actule.git", branch = "master", version = "0.4.6"}
