[package]
name = "squack"
version = "0.5.0"
authors = ["Kiley Owen <yelikdev@gmail.com>"]

[dependencies]
actule = {git = "https://github.com/yeliknewo/actule.git", branch = "image"}
find_folder = "0.3.0"
